### ISSUE TITLE
Read-only mode for ReplayClient

### ISSUE THREAD

**Issue by palfrey** [leoschwarz/reqwest_mock#12]
It would be really useful to have a read-only mode for ReplayClient. This means you can do things like write a bunch of responses in local testing, commit them to source control, and then enable read-only mode in CI so it only uses the responses that are already written.

I've used features like this in [VCR.py](https://vcrpy.readthedocs.io/) which has a variety of useful ["record modes"](https://vcrpy.readthedocs.io/en/latest/usage.html#record-modes) like this

**Comment by leoschwarz** [comment]
Yes that would be definitely nice to have, thanks for the suggestion. I don't have the time for this now but maybe in 2-3 weeks I'll come back to it. (I guess the crate might be in need of a bit of a overhaul too.)

**Comment by leoschwarz** [comment]
wip implementation on https://github.com/leoschwarz/reqwest_mock/tree/replay_mode

It will still need some testing before adding it to the crate functionality.

**Comment by leoschwarz** [comment]
One caveat is that it would also need to handle serialization format changes, like currently it would be possible to update these files without care because if we bump the version number the requests will simply be re-run, but if users specify a read-only mode this will result in an error and require manual intervention.

Also I wonder if it wouldn't be more sensible to allow passing this choice as an environment variable (because you will have to record the casettes/replay data before the first run), however, this approach is problematic if someone wants to have multiple replay clients in a single project. Of course I could also add the vcr style once replay mode, however it would add even more complexity to the replay client.
