### ISSUE TITLE
Using a function from request to response to mock

### ISSUE THREAD

**Issue by Ploppz** [leoschwarz/reqwest_mock#30]
Wondering if you agree that this would be nice, in which case I can try to implement it.

Looking at the `StubClient`, it seems only able to serve a given static response for given request parameters (URL etc).
I find myself in a somewhat more complex situation where I would like to mock a service which gives a response that depends on the request (e.g. a field from the request body would appear in the response body).

So my suggestion is for `ResponseStubber` to have a function like
```
pub fn body_with<B: Into<Body>, F: Fn(Method, Body, HeaderMap) -> B>(self, body: F) -> Self
```

Or should I create a new client struct (not StubClient) for this?

**Comment by leoschwarz** [comment]
Hello, thank you for your interest in this crate. I like your proposal and it makes sense to include it directly in the ResponseStubber because it would be combineable with the other functions there.

At this time, I'm only passively maintaining this repository. It's also not yet updated to reqwest 0.11. You might want to check out these issues too for the context of this crate:

- https://github.com/seanmonstar/reqwest/issues/154
- https://github.com/seanmonstar/reqwest/issues/155

To save time, I'd personally recommend to try wiremock instead, I think it should support the scenario you want: https://docs.rs/wiremock/0.4.9/wiremock/trait.Respond.html#dynamic-responses

However, I haven't personally used it yet.

**Comment by Ploppz** [comment]
Thanks for the suggestion, I will give wiremock a try!

**Comment by leoschwarz** [comment]
Thank you for your interest in this project.
This project was a proof of concept to create a generic interface for the Rust reqwest crate that would allow users to mock and record and replay HTTP requests for testing purposes.

This project is no longer updated or maintained and this repository will be archived.

The following non-exhaustive list of alternative solutions are recommended instead to mock HTTP requests in Rust (as of 18.5.2023):

- https://github.com/chorusone/rvcr
- https://github.com/lukemathwalker/wiremock-rs
- https://github.com/beltram/stubr
- https://github.com/alexliesenfeld/httpmock
- https://github.com/lipanski/mockito
